#
# ROS bag dataset config
# 
measurements:
    lidar:
        topic_name: /kitti/velo/pointcloud
        frame_id: velo_link
        queue_size: 1000000
    imu:
        topic_name: /kitti/oxts/imu
        frame_id: imu_link
        queue_size: 10000000
    gnss:
        topic_name: /kitti/oxts/gps/fix
        frame_id: imu_link
        queue_size: 10000000
    velocity:
        topic_name: /kitti/oxts/gps/vel
        frame_id: imu_link
        queue_size: 10000000

    